/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const FleetsViewRouteLazyImport = createFileRoute('/fleets-view')()

// Create/Update Routes

const FleetsViewRouteLazyRoute = FleetsViewRouteLazyImport.update({
  path: '/fleets-view',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/fleets-view/route.lazy').then((d) => d.Route),
)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/fleets-view': {
      preLoaderRoute: typeof FleetsViewRouteLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  FleetsViewRouteLazyRoute,
])

/* prettier-ignore-end */
